name: project_env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision=0.17.1
  - cudatoolkit=11.3 
  - pip:
      - pillow>=9.0.0  
      - jupyter  
      - ipykernel  
