name: project_env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.14
  - pandas=2.2.1
  - pillow=10.2.0
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - pytorch=2.2.1
  - torchvision=0.17.1
  - pip
  - pip:
      - torch==1.13.0
